name: Configure Secret Token
run-name: $Deploy Secret Token
on: 
  push:
  workflow_dispatch:

jobs:
  Deploy-Token:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trying to use a template to set a token in deploy time."
      - uses: actions/checkout@v3

      - name: Create the creds file
        env:
          TOKEN: '${{ secrets.SECRET_TOKEN }}'
        run: envsubst < conf/secrets.conf.tpl > conf/secrets.conf

      - name: Show credentials
        run: cat conf/secrets.conf